#! /bin/bash

./repull-build
cd ./build || exit
cp -rf ../.git-static ./.git
git add .
git commit -m 'rebuild'
git push
rm -rf ../.git-static
cp -rf ./.git ../.git-static

cd ..
git add ./.git-static
git commit -m 'build branch git update'
git pull || exit
git push

exit
