#! /bin/bash

git clone https://github.com/DavidTeju/DavidTeju.github.io.git
rm -rf ./build
mv ./DavidTeju.github.io ./build
cd build || exit
git checkout build
git pull
rm -rf ../.git-static
mv ./.git ../.git-static
